### PR TITLE
Update form Java 8 to Java 11

### PR DESCRIPTION
**Pull request by ZeusDev02**
- Update form openjdk-8-jdk-headless to openjdk-8-jdk-headless
- Use openjdk:11-jre-buster instead of openjdk:8-jre-alpine as runtime environment inside the docker container
- Grammar fixes in README.md
- Whitespace fix in start.sh

### CODE REVIEW

**Comment by Erikvl87** [comment]
Thank you for this PR. Please give me some time to review your changes regarding the base images. I'll get back to you asap.

Note that some of the grammar fixes you are proposing are quotes from the official Languagetool website.

**Comment by Erikvl87** [comment]
I couldn't get your version of the Dockerfile to build. For #15 I also had to upgrade the base image, so that work is done in commit https://github.com/Erikvl87/docker-languagetool/commit/9ccdfcea1d0faba4cefa7bc474980965d41bcd71.

`java -version` produces:
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)
```

Does this resolve your main concern of updating Java 8 to 11?

**Comment by Erikvl87** [comment]
This morning I changed the base image again. This time from `openjdk:11-jre-buster` to `alpine`, but kept the upgrade to Java 11:

```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-alpine-r1)
OpenJDK 64-Bit Server VM (build 11.0.9+11-alpine-r1, mixed mode)
```

The image has been pushed to Docker Hub under the tag `5.2.3-dockerupdate-2`.

**Comment by ZeusDev02** [comment]
Hi Erik,
Thank you for the review and the time invested.
To answer your question, yes, it solves my main concern, upgrading Java 8 to 11.

Since the changes are already in the master branch, this pull request can be closed.

Thank you
Cheers Alex

**Pull request closed without merging**
